version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self-jobs-range.yml

env:
  global:
    - REQUIRE_EXTRA="silverstripe/versioned:1.8.x-dev"
    - PHPUNIT_SUITE="cwp-recipe-core"
